name = "ModelAirRaces"
uuid = "e42d41ef-a387-496c-ae09-8d4b0687c38e"
authors = ["Jean de Becdelievre"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
